version: '3'
services:
    engine:
        build: "."
        # depends_on:
        #    - polyswarmd
        environment:
            - POLYSWARM_HOST=polyswarmd
        volumes:
            - "contract:/flag" 
volumes:
    contract:
