version: '2'
services:
  artifact_index:
    image: "polyswarm/artifact-index"
    ports:
      - "9696:9696"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URI=postgresql://postgres:password@aipostgres:5432/postgres
      - POLY_WORK=testing
      - DEFAULT_COMMUNITY=gamma
      - AI_S3_ENDPOINT=http://minio:9000/
      - AI_S3_BUCKET=testing
      - AI_S3_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - AI_S3_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AI_SECRET_KEY=TOOMANYSECRETS
      - FLASK_WORKERS=4
    command:
      - "dockerize"
      - "-wait"
      - "tcp://aipostgres:5432"
      - "-wait"
      - "tcp://minio:9000"
      - "-timeout"
      - "1000s"
      - "./docker/run.sh"
      - "-m"
  aipostgres:
    image: "postgres:11.2"
    environment:
      - POSTGRES_PASSWORD=password
  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /export/testing && /usr/bin/minio server /export'
    environment:
          MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
          MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

    ports:
        - "9000:9000"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.6.0"
    environment:
        - "discovery.type=single-node"
    ports:
        - "9200"