version: '2'
services:

  microengine-eicar_frontend:
    image: "polyswarm/polyswarm-client:latest"
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/microengine_keyfile
      - PASSWORD=password
      - REDIS_ADDR=redis:6379
      - QUEUE=microengine-eicar
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "microengine"
      - "--log"
      - "INFO"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--backend"
      - "producer"
      - "--chains"
      - "side"

  microengine-eicar_worker:
    image: "polyswarm/polyswarm-client:latest"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - QUEUE=microengine-eicar
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-wait"
      - "tcp://redis:6379"
      - "-timeout"
      - "1000s"
      - "worker"
      - "--log"
      - "INFO"
      - "--testing"
      - "10"
      - "--backend"
      - "eicar"

  microengine-eicar_deposit:
    image: "polyswarm/polyswarm-client:latest"
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/microengine_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "balancemanager"
      - "--log"
      - "info"
      - "deposit"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "100000"

networks:
  default:
    external:
      name: orchestration_default
