version: '2'
services:

  microengine:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/microengine_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "microengine"
      - "--log"
      - "info"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--backend"
      - "multi"
      - "--chains"
      - "side"

  deposit-microengine:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/microengine_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "balancemanager"
      - "--log"
      - "info"
      - "deposit"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "100000"

networks:
  default:
    external:
      name: orchestration_default