version: '2'
services:
  polymon-global:
    image: "polyswarm/poly-mon"
    depends_on:
      - polyswarmd
    environment:
      - PASSWORD=password
      - PYTHON_UNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=text
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "poly-mon"
      - "--reporter-type"
      - "global"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--keyfile"
      - "local_keyfile"
      - "--dd-api-key"
      - "${PS_DATADOG_APIKEY_POLYMON}"
      - "--local-testing"
      - "--eth-addrs"
      - "homechain:8545"
      - "--consul-url"
      - "http://consul:8500"
      - "--poly-work"
      - "stage"

  polymon-community:
    image: "polyswarm/poly-mon"
    depends_on:
      - polyswarmd
    environment:
      - PASSWORD=password
      - PYTHON_UNBUFFERED=1
      - MALICIOUS_BOOTSTRAP_URL=https://corpora.sfo2.digitaloceanspaces.com/pdfs-1000
      - ARCHIVE_PASSWORD=icanhazmalware
      - POLY_COMMUNITY_NAME=gamma
      - POLY_WORK=${POLY_WORK}
      - LOG_LEVEL=INFO
      - PYTHONASYNCIODEBUG=1
      - LOG_FORMAT=json
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "poly-mon"
      - "--reporter-type"
      - "community"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--consumer-addr"
      - "consumer_frontend:12322"
      - "--insecure-transport"
      - "--keyfile"
      - "local_keyfile"
      - "--dd-api-key"
      - "${PS_DATADOG_APIKEY_POLYMON}"
      - "--local-testing"
      - "--eth-addrs"
      - "sidechain:8545"

