#
# This file should be combined with dev.yml and tutorial.yml such as:
#
# $ docker-compose -f dev.yml -f tutorial.yml -f test.yml up
#
#
version: '3'
services:
  ambassador:
    image: "polyswarm/ambassador"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - ADDRESS=0x4b1867c484871926109e3c47668d5c0938ca3527
      - POLYSWARMD_HOST=polyswarmd:31337
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "ambassador"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--keyfile"
      - "docker/keyfile"
      - "--password"
      - "password"
      - "--backend"
      - "eicar"
  arbiter:
    image: "polyswarm/arbiter"
    depends_on:
      - polyswarmd
      - homechain
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "arbiter"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--keyfile"
      - "docker/keyfile"
      - "--password"
      - "password"
      - "--backend"
      - "verbatim"
  microengine:
    image: "polyswarm/microengine"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "microengine"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--keyfile"
      - "docker/keyfile"
      - "--password"
      - "password"
      - "--backend"
      - "scratch"
