#
# This file should be combined with dev.yml and tutorial.yml such as:
#
# $ docker-compose -f dev.yml -f tutorial.yml -f test.yml up
#
#
version: '3'
services:
  ambassador:
    image: "polyswarm/ambassador"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY_HOST=apikeymgmt:5000
      - EMAIL=ambassador@polyswarm.io
      - ADDRESS=0x4b1867c484871926109e3c47668d5c0938ca3527
      - POLYSWARMD_HOST=polyswarmd:31337
    command: "./scripts/wait_and_run.sh"
  arbiter:
    image: "polyswarm/arbiter"
    depends_on:
      - polyswarmd
      - homechain
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY_HOST=apikeymgmt:5000
      - EMAIL=arbiter@polyswarm.io
      - POLYSWARMD_HOST=polyswarmd
      - POLYSWARMD_PORT=31337
      - ADDRESS=0xf870491ea0f53f67846eecb57855284d8270284d
      - PASSWORD=password
      - CHAIN=home
    command: "./scripts/wait_and_test.sh"
  microengine:
    image: "polyswarm/microengine"
    depends_on:
      - polyswarmd
    environment:
      - POLYSWARMD_HOST=polyswarmd
      - POLYSWARMD_PORT=31337
      - POLYSWARMD_ADDR=polyswarmd:31337
    command: "./scripts/wait_and_test.sh"
