#
# This file should be combined with polyswarmd.yml and contract.yml such as:
# 
# $ docker-compose -f polyswarmd.yml -f contract.yml -f test.yml up
#
# 
version: '3'
services:
  ambassador:
    image: "polyswarm/ambassador"
    depends_on:
      - polyswarmd
    environment:
      - AMBASSADOR_HOST=http://ambassador:342
      - POLYSWARM_HOST=http://polyswarm:31337

  arbiter_verbatim:
    image: "polyswarm/arbiter-verbatim"
    depends_on:
       - polyswarmd
    environment:
      - ARBITER_HOST=http://arbiter_verbatim:352
      - POLYSWARM_HOST=http://polyswarm:31337
