#
# This file should be combined with dev.yml and tutorial.yml such as:
# 
# $ docker-compose -f dev.yml -f tutorial.yml -f test.yml up
#
# 
version: '3'
services:
  ambassador:
    image: "polyswarm/ambassador"
    depends_on:
      - polyswarmd
    environment:
      - POLYSWARM_HOST=polyswarmd
      - POLYSWARM_PORT=31337
#    network_mode: "host"
    command: "./wait_and_run.sh"
    

