version: '3'
services:
    tutorial:
        image: "polyswarm/microengine"
        depends_on:
            - polyswarmd
        environment:
           - POLYSWARMD_HOST=polyswarmd
           - POLYSWARMD_PORT=31337
           - POLYSWARMD_ADDR=polyswarmd:31337
        command: "./scripts/wait_and_clam.sh"
