version: '2'
services:
  ambassador:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/ambassador_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "ambassador"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--backend"
      - "eicar"
  arbiter:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/arbiter_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "arbiter"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--backend"
      - "verbatim"
  microengine:
    image: "polyswarm/polyswarm-client"
    depends_on:
      - polyswarmd
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/microengine_keyfile
      - PASSWORD=password
      - CLAMD_HOST=clamav
      - CLAMD_PORT=3310
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "microengine"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--backend"
      - "eicar"
