version: '3'
services:
    #
    # the tutorial.yml builds here since docker push did not work 
    # at this point.     
    #
    engine:
        build: "."
        depends_on:
           - polyswarmd
        environment:
            - POLYSWARM_HOST=polyswarmd
        volumes:
            - "contract:/flag" 
volumes:
    contract:
